### ISSUE TITLE
Error building wallet from source (ubuntu)

### ISSUE THREAD

**Issue by ghost** [Harold-Coin/haroldcoin-main-23-may#1]
Thank you for attempting to create instructions on how to build from source! It really helps inexperienced people like me! Small issue, I believe your instructions are out of date / broken

For one 
You write
`git clone https://github.com/Harold-Coin/haroldcoin-main.git --recursive`
However if you examine the names you will notice that haroldcoin-main is incorrect its haroldcoin-main-23-may
This also means the "cd haroldcoin" is false because actually its "cd haroldcoin-main-23-may"

For a new person (such as myself) this can be confusing or even result in someone not being able to follow your instructions if they dont know any better.

For two 
https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin

This repository seems dead so not able to execute command to install it. 

Right now I am looking for solutions - I hope you can revise the build instructions for ubuntu when you get a chance.

**Comment by ghost** [comment]
Unable to find a solution so far, not able to build from source. Not able to execute sudo add-apt-repository ppa:bitcoin/bitcoin as well.

**Comment by BenLangers** [comment]
Hi, that seems to be a very old version indeed. There is no build necessary, the binaries for ubuntu 18 are available in the repo. Will check and update procedures asap, currently in the middle of a move, but feel free to hit me up on TG itmt.

**Comment by ghost** [comment]
> Hi, that seems to be a very old version indeed. There is no build necessary, the binaries for ubuntu 18 are available in the repo. Will check and update procedures asap, currently in the middle of a move, but feel free to hit me up on TG itmt.

So there will no longer be any build instructions? Nobody uses 18 anymore except people who are devs that dont ever talk to end users. 20 and 22 are the supported LTS versions for ubuntu please consider modernizing and future proofing this project. 

Is it no longer possible to write instructions for how to build this wallet from source? I thought it was a great idea and wish we can preserve the contribution to open source. 

Relying on an already out of date binary for the future wont be great. 18 was already old when you created the 18 binary - it should have been made for 20 and 22.

**Comment by ghost** [comment]
> Hi, that seems to be a very old version indeed. There is no build necessary, the binaries for ubuntu 18 are available in the repo. Will check and update procedures asap, currently in the middle of a move, but feel free to hit me up on TG itmt.

If you can assist me to build the binary for ubuntu 20 I would be more than happy to share it. I can show you which part of the make process im stuck on.
